CREATE DATABASE IF NOT EXISTS military_asset_management;
USE military_asset_management;

-- The application uses Hibernate ddl-auto=update and will create/maintain tables.
-- This dump also provides reference seed data. Passwords are generated by the application
-- using BCrypt, so use the application startup seed for the demo users.

INSERT INTO bases (id,name,location) VALUES
(1,'Bangalore Base','Bangalore'),
(2,'Chennai Base','Chennai'),
(3,'Hyderabad Base','Hyderabad')
ON DUPLICATE KEY UPDATE name=VALUES(name), location=VALUES(location);

INSERT INTO equipment_types (id,name,category) VALUES
(1,'Vehicle','Transport'),
(2,'Weapon','Arms'),
(3,'Ammunition','Consumable'),
(4,'Communication Equipment','Communication')
ON DUPLICATE KEY UPDATE name=VALUES(name), category=VALUES(category);
